language: go
sudo: false

go:
  - 1.6
  - 1.7
  - tip

cache:
  directories:
  - vendor

install:
  - mkdir $GOPATH/bin
  - curl https://glide.sh/get | sh
  - glide install

script:
  - go test -v -bench=. -benchmem $(glide nv) | tee test.out
  - go run main.go -in test.out

notifications:
  email: false
