language: go
sudo: false

go:
  - 1.6
  - 1.7
  - tip

env:
  global:
    - GOBENCH_URL: http://bench.bign8.info

cache:
  directories:
  - vendor
  - $GOPATH/bin
  - $HOME/.glide

before_install:
  - openssl aes-256-cbc -K $encrypted_18ef70bdcdac_key -iv $encrypted_18ef70bdcdac_iv -in secret.json.enc -out secret.json -d

install:
  - curl https://glide.sh/get | sh
  - if [[ "$TRAVIS_GO_VERSION" == "tip" ]]; then glide update; cat glide.lock; else glide install; fi

script:
  - go test -v -bench=. -benchmem $(glide nv) | tee test.out
  - go run main.go -in test.out

# deploy:
#   provider: gae
#   # Skip cleanup so api_key.py and vendored dependencies are still there
#   skip_cleanup: true
#   keyfile: secret.json
#   project: gobench-141403
#   config: web/app.yaml
#   default: true
#   verbosity: debug
#   on:
#     all_branches: true

notifications:
  email: false
